version: '3.8'
services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 'admin'
      RABBITMQ_DEFAULT_PASS: 'password'
    ports:
      - "5672:5672"
      - "15672:15672"
      - "5552:5552"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"

volumes:
  rabbitmq_data:
